clang-tidy: ignore modernize-make-unique and cert-err60-cpp
- make_unique is only available with C++14
- cert-err60-cpp was raised for:
  error: thrown exception type is not nothrow copy constructible
               throw std::out_of_range("Bad Test Name");
  However this is an std::exception, and thus it should be noexcept already.